import { Inter } from "next/font/google";
import { ModalProvider } from "../components/Modal/Modal";
import Modals from "../components/modals/Modals";
import Link from "next/link";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/">Home</Link>
        <Link href="/about">About</Link>
        <ModalProvider>
          {children}
          <Modals />
        </ModalProvider>
      </body>
    </html>
  );
}
